version: "2.0"
services:
  rtorrent:
    image: linuxserver/rutorrent:arm32v7-v3.9-ls47
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8070:80
      - 51413:51413
      - 6881:6881/udp
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    restart: unless-stopped