version: '2.0'

services:
  vsftpd:
#    image: panubo/vsftpd # esta imagen sirve para amd64
    image: pablokbs/panubo-vsftpd-arm # esta imagen es para ARM (raspberry)
    environment:
      - FTP_USER=respeaker
      - FTP_PASSWORD=respeaker
    volumes:
      - /home/respeaker/mnt:/srv
    expose:
      - 21
    network_mode: host